name: PullRequest

on: [pull_request]

jobs:
  buildMod:
    name: build plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD
      - name: build plugin
        run:  ./gradlew build -S
      - name: grab artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: WorldGuardPlugin-${{steps.tagger.outputs.tag}}
          path: |
            ./**/build/libs/*.jar
            !buildSrc/build/libs/*.jar
          if-no-files-found: error
